# Generated by Django 4.2.16 on 2024-10-19 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0002_room_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
