# Generated by Django 4.2.16 on 2024-10-19 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0004_message_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='date',
        ),
        migrations.RemoveField(
            model_name='message',
            name='room',
        ),
    ]
